### ISSUE TITLE
How model learn uncertainty

### ISSUE THREAD

**Issue by LinyeLi60** [wzzheng/IDML#2]
Hi Chengkun, your work is very novelty, I have a question that how the model learn uncertainty because there is no ground truth uncertainty label provided.

**Comment by wzzheng** [comment]
Thanks for your interest! We create uncertainty samples using mixup, e.g., to mix an image A with B. If we pull the embedding e of this mixed sample closer to both class centers c_A and c_B, the network will have to learn to enlarge the uncertainty to achieve this. This is because an embedding e cannot equal both c_A and  c_B at the same time. But in our proposed introspective metric d_intro, we can enlarge the uncertainty to make both d(e, c_A) and d(e, c_B) small.

Feel free to ask more questions!
